### ISSUE TITLE
Install error wrtc related

### ISSUE THREAD

**Issue by kblockdev** [seanjameshan/coin-cli#1]
@seanjameshan hi, need help here is the logs 

System is Ubuntu 16.10 (GNU/Linux 4.8.0-22-generic i686)

node-pre-gyp ERR! Tried to download(undefined): https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.63/Release/node-v59-linux-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for wrtc@0.0.63 and node@9.2.1 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/med/ccli/node_modules/wrtc/build'
gyp ERR! System Linux 4.8.0-22-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32/wrtc.node" "--module_name=wrtc" "--module_path=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32"
gyp ERR! cwd /home/med/ccli/node_modules/wrtc
gyp ERR! node -v v9.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32/wrtc.node --module_name=wrtc --module_path=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32' (1)
node-pre-gyp ERR! stack at ChildProcess. (/home/med/ccli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.8.0-22-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/med/ccli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/med/ccli/node_modules/wrtc
node-pre-gyp ERR! node -v v9.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32/wrtc.node --module_name=wrtc --module_path=/home/med/ccli/node_modules/wrtc/build/wrtc/v0.0.63/Release/node-v59-linux-ia32' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.0.63 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.0.63 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/med/.npm/_logs/2018-02-09T08_24_27_265Z-debug.log

**Comment by seanjameshan** [comment]
did you try sudo?

**Comment by kblockdev** [comment]
@seanjameshan yes with sudo

**Comment by markandrus** [comment]
There are no ia32 builds of wrtc at this time, only 64-bit builds. That is why the download fails. `sudo` will not help.

**Comment by lethucuyen** [comment]
Still no answer to the question, and I have the same problem? 

> There are no ia32 builds of wrtc at this time, only 64-bit builds. That is why the download fails. `sudo` will not help.

Still no answer to the question, and I have the same problem?
